modLoader="kotlinforforge"
loaderVersion="${loaderVersionRange}"
license="MIT"
issueTrackerURL="https://github.com/BlueSheep2804/ToggleVisualize/issues"

[[mods]]
modId="togglevisualize"
version="${version}"
displayName="Toggle Visualize"
logoFile="assets/togglevisualize/icon.png"
authors="BlueSheep2804"
description="Visualize sprint and sneak toggling."
displayTest="IGNORE_ALL_VERSION"

[[dependencies.togglevisualize]]
modId="forge"
mandatory=true
versionRange="${forgeVersionRange}"
ordering="NONE"
side="BOTH"

[[dependencies.togglevisualize]]
modId="minecraft"
mandatory=true
versionRange="${minecraftVersionRange}"
ordering="NONE"
side="BOTH"

[[dependencies.togglevisualize]]
modId="yet_another_config_lib_v3"
mandatory=true
versionRange="*"
ordering="AFTER"
side="BOTH"
