name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - BlueSheep2804
body:
  - type: checkboxes
    id: duplicate-check
    attributes:
      label: Have you checked for similar issues?
      description: Please search the [issue list](https://github.com/BlueSheep2804/ToggleVisualize/issues) to make sure your bug hasn't already been reported.
      options:
        - label: I have confirmed there are no duplicate issues
          required: true
  - type: checkboxes
    id: minimum-configuration
    attributes:
      label: Did you reproduce the bug with a minimal configuration?
      description: Please verify the bug occurs with only this mod installed, to rule out conflicts with other mods.
      options:
        - label: I was able to reproduce the bug with a minimal configuration
          required: true
  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: Which version of Minecraft are you using?
      placeholder: e.g. 1.21.1
    validations:
      required: true
  - type: input
    id: mod-version
    attributes:
      label: ToggleVisualize Version
      description: Which version of this mod are you using?
      placeholder: e.g. v1.2.3
    validations:
      required: true
  - type: input
    id: modloader
    attributes:
      label: ModLoader Type and Version
      description: Which ModLoader (Fabric/Forge/NeoForge, etc.) and version are you using?
      placeholder: e.g. Fabric 0.15.7
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the bug, in order.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: e.g. The GUI should open when pressing the button
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: e.g. Nothing happens when pressing the button
    validations:
      required: true
  - type: textarea
    id: crash-report
    attributes:
      label: Crash Report / Logs
      description: If you have a crash report or relevant logs, please upload them to [https://mclo.gs](https://mclo.gs) and paste the link here.
      placeholder: https://mclo.gs/______
  - type: textarea
    id: combination
    attributes:
      label: Other Mods Installed
      description: List any other mods (with versions) that were installed when the issue occurred.
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots / Videos
      description: If possible, attach images or videos that show the issue.
  - type: markdown
    attributes:
      value: |
        Thank you for your cooperation! We will do our best to address your report as soon as possible.
