name: Release
on:
  workflow_dispatch: # Manual trigger
    inputs:
      name:
        description: 'Version name / "Mods" = All versions'
        required: false
        default: Mods
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: make gradlew executable
        run: chmod +x ./gradlew
      - name: build and publish mods
        run: ./gradlew build publish$VERSION_NAME
        env:
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          VERSION_NAME: ${{ inputs.name }}
